# Global configuration. These configuration parameters should be valid for all
# portals. Don't edit unless you want to impact all the portals.

[dest]
help = "{infra_dir}/{type}/{portal}/help/"
help_texts = "{infra_dir}/{type}/{portal}/help/texts/"
img = "{infra_dir}/{type}/{portal}/img/"
json = "{infra_dir}/{type}/{portal}/json/"
map = "{infra_dir}/{type}/{portal}/map/"
help_images = "{infra_dir}/{type}/{portal}/help/img/"
output = "{infra_dir}/{type}/{portal}"
print = "{infra_dir}/{type}/{portal}/print/"
search = "{infra_dir}/{type}/search/"
search_portal = "{infra_dir}/{type}/{portal}/search/"
services = "{infra_dir}/{type}/{portal}/json/"
template_search_portal_locations = "{infra_dir}/{type}/{portal}/search/portal-{portal}.conf"
template_translate_catalog = "{infra_dir}/{type}/{portal}/json/catalog_{{topic}}_{{lang}}.json"
translate = "{infra_dir}/{type}/{portal}/locales/"
vhost = '{infra_dir}/{type}/vhosts.d/{portal}.conf'

[dest.geo_front3]
appcache = '{infra_dir}/prod/{portal}/geoadmin.appcache'
deps = 'test/deps'
karma_conf = 'test/karma-conf.{type}.js'
plugins_file = 'src/js/Gf3Plugins.js'
protractor_conf = 'test/protractor-conf.{type}.js'
template_cache_module = 'src/TemplateCacheModule.js'


[print.mapHeight.A1]
landscape = 1482
portrait = 2175
[print.mapWidth.A2]
landscape = 1558
portrait = 1064
[print.mapHeight.A4]
landscape = 525
portrait = 725
[print.mapHeight.A2]
landscape = 985
portrait = 1475
[print.mapWidth.A0]
landscape = 3241
portrait = 2254
[print.mapHeight.A0]
landscape = 2173
portrait = 3155
[print.mapWidth.A4]
landscape = 725
portrait = 525
[print.mapHeight.A3]
landscape = 715
portrait = 1005
[print.mapWidth.A3]
landscape = 1005
portrait = 715
[print.mapWidth.A1]
landscape = 2255
portrait = 1558


[src]
base_include = "{infra_dir}/"
external_layers = "{infra_dir}/json/{portal}/external/*.json"
img = [ "img/*.png", "img/*.gif", "img/*.jpg", "img/*.jpeg", "img/maki",]
img_portal = "{infra_dir}/img/{portal}/*"
help = "help/*"
help_common_folder = "{infra_dir}/help/common"
help_images_folder = "{infra_dir}/help/{portal}/img/"
help_logo = "{infra_dir}/img/{portal}/{portal}.jpg"
help_original_images_folder = "help/img/"
help_original_texts_folder = "help/texts/"
help_portal_folder = "{infra_dir}/help/{portal}"
help_texts_folder = "{infra_dir}/help/{portal}/texts/"
map_path = "{type}/{portal}/map/portals/{portal}.map"
print = "{infra_dir}/print/*.in*"
print_logo = "{infra_dir}/print/{portal}/*.*"
search = "search/*.in*"
search_db = "search/common/db.in.conf"
search_portal_layers = "search/common/search-layers.in.conf"
search_portal_locations = "{infra_dir}/search/portal-locations.in.conf"
search_tsv_files = "{infra_dir}/{type}/{portal}/search/*.tsv"
topics = "{infra_dir}/json/{portal}/topics/*.json"
translate_catalog = "{infra_dir}/translations/catalog.csv"
translation_files = [
    "https://docs.google.com/spreadsheets/d/1F3R46w4PODfsbJq7jd79sapy3B7TXhQcYM7SEaccOA0/export?format=csv&gid=0",
    "translations/common.csv",
    "{infra_dir}/translations/common.csv",
    "{infra_dir}/translations/{portal}.csv"
]
translate_ignore = "{infra_dir}/translations/ignore.csv"
vhost = 'apache/vhost.jinja2.conf'

[src.geo_front3]
appcache = 'src/geoadmin.nunjucks.appcache'
index = 'src/index.nunjucks.html'
karma_conf_template = 'test/karma-conf.nunjucks.js'
partials = 'src/components/**/partials/**/*.html'
plugins = 'src/plugins/*.js'
plugins_template = 'src/Gf3Plugins.nunjucks.js'
protractor_conf_template = 'test/protractor-conf.nunjucks.js'
template_cache_module = 'src/TemplateCacheModule.nunjucks.js'


[test.karma]
browsers = ['Firefox', 'Chrome']

[test.protractor]
test_portal_address = 'http://localhost'
generate_coverage_report = true
